### ISSUE TITLE
NoClassDefFoundError: : com/tinkerpop/gremlin/structure/Graph$System

### ISSUE THREAD

**Issue by szimon** [mpollmeier/gremlin-scala#62] opened 2015-02-04 17:01 UTC
A problem occurs in version 3.0.0.M7. Works fine with M.0.0.6c

```
name := "test-gremlin-scala"

version := "1.0"

scalaVersion := "2.11.5"

libraryDependencies ++= Seq(
  "com.michaelpollmeier"       %% "gremlin-scala"   % "3.0.0.M7",
  "com.thinkaurelius.titan"    %  "titan-core"      % "0.9.0-M1",
  "com.thinkaurelius.titan"    %  "titan-cassandra" % "0.9.0-M1",
  "com.thinkaurelius.titan"    %  "titan-es"        % "0.9.0-M1"
)
```

Test file:
```
import com.thinkaurelius.titan.core.{TitanFactory, TitanGraph}
import com.tinkerpop.gremlin.scala.GremlinScala
import org.apache.commons.configuration.BaseConfiguration

object App {
  def main(args: Array[String]) = {
    val g = createSimpleTestGraphWithGremlinScala()
    println(g)
  }

  def createSimpleTestGraphWithGremlinScala(): TitanGraph = {
    val newGraph = createEmptyInMemoryGraph()

    val gs = GremlinScala(newGraph)

    val v1 = gs.addVertex("v1")
    val v2 = gs.addVertex("v2")
    v1.addEdge("uses", v2, Map())

    newGraph
  }

  def createEmptyInMemoryGraph(): TitanGraph = {
    val conf = new BaseConfiguration()
    conf.addProperty("storage.backend", "inmemory")
    val newGraph = TitanFactory.open(conf)
    newGraph
  }
}
```

An attempt to add a vertex (`val v1 = gs.addVertex("v1")`) results in 
`NoClassDefFoundError: : com/tinkerpop/gremlin/structure/Graph$System  (Token.java:35)`

**Comment by mpollmeier** [comment] 2015-02-05 22:26
duplicate of https://github.com/mpollmeier/gremlin-scala-examples/issues/7

**Closed by mpollmeier** 2015-02-05 22:26 UTC
